### ISSUE TITLE
`make test` is not terminating

### ISSUE THREAD

**Issue by izgzhen** [MarkGaox/soot-skeleton#20]

**Comment by MarkGaox** [comment]
It seems like it takes longer than we expect for it to infer the correct call graph configuration. But it does terminates. And I found an interesting fact that the inference terminates much faster if we run the 4 unit tests separately.

> TESTING CALL GRAPH
Parsing: <DemoClass: void <init>()>
Parsing: <DemoClass: void <init>(int)>
Parsing: <DemoClass: void <init>(DemoClass)>
Parsing: <DemoClass: void s1()>
Parsing: <DemoClass: void i1()>
Parsing: <DemoClass: void s2()>
Parsing: <DemoClass: void i2()>
Parsing: <DemoClass: void overloadTester()>
Parsing: <DemoClass: void overload(byte)>
Parsing: <DemoClass: void overload(short)>
Parsing: <DemoClass: void overload(int)>
Parsing: <DemoClass: void overload(long)>
Parsing: <DemoClass: void overload(float)>
Parsing: <DemoClass: void overload(double)>
Parsing: <DemoClass: void overload(char)>
Parsing: <DemoClass: void overload(boolean)>
Parsing: <DemoClass: void main(java.lang.String[])>
Validating generated output ------------------------------------>
WHOLE_PROGRAM : true
ALLOW_PHANTOM_REF : true
SET_APP : false
CG_Safe_New_Instance : false
CG_Cha_Enabled : false
CG_Spark_Enabled : true
CG_Spark_Verbose : false
CG_Spark_OnFlyCg : false
IGNORE_RESOLUTION : false
VERBOSE : false
NOBODY_EXCLUDED : false

> [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,186.325 s - in unit.AppTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  19:50 min
> [INFO] Finished at: 2020-01-31T11:41:20-08:00
> [INFO] ------------------------------------------------------------------------
