### ISSUE TITLE
Use git submodule for android-platforms

### ISSUE THREAD

**Issue by izgzhen** [MarkGaox/soot-skeleton#3]
https://github.com/izgzhen/android-platforms

Steps:

1. Remove your current `android-platforms` folder and commit the change
2. `git submodule add https://github.com/izgzhen/android-platforms` and commit the change

**Comment by MarkGaox** [comment]
Just get it done. Thanks! By the way, can you take a look at the issue #4 ? I met an error when parsing java class using soot.
