### ISSUE TITLE
Can't solve the error when loading Java Class with Soot in Analysis.java

### ISSUE THREAD

**Issue by MarkGaox** [MarkGaox/soot-skeleton#4]
When running Analysis.java, it keeps failing on loading the DemoClass.java. 
![Screen Shot 2019-09-30 at 8 15 23 PM](https://user-images.githubusercontent.com/32374858/65931669-8fa93300-e3bf-11e9-83c1-d7080aa9eec1.png)

**Comment by MarkGaox** [comment]
https://github.com/MarkGaox/soot-skeleton/blob/master/src/main/java/SootExample/Analysis.java is over here.

The problem is it doesn't successfully parse the DemoClass.java, which is located in test-resource, as we expected. All methods inside DemoClass after parsing are missing, so it throws an error that it can't find the main method.

**Comment by izgzhen** [comment]
https://github.com/MarkGaox/soot-skeleton/blob/f0d9f3ee6b5996af07946bda7017998dbc7606e9/src/main/java/SootExample/Analysis.java#L51

it means that you load the code you want to analyze from class file. e.g. DemoClass.class. You need to use `javac` to compile it.

**Comment by izgzhen** [comment]
@MarkGaox Can you write a step-by-step set up guide (similar to https://izgzhen.github.io/seguard-www/developer.html and https://izgzhen.github.io/seguard-www/quickstart.html) in `README.md` and ping me back as soon as you are done?

**Comment by MarkGaox** [comment]
Sorry for the lateness, the new developer setting up guide is online now and can be found here https://github.com/MarkGaox/soot-skeleton-resources. Please check it out. And I will keep updating it during the developing process.

**Comment by izgzhen** [comment]
I will try out ASAP. BTW, I really appreciate your work and it looks like
you have been spending a lot of time to
set up the sphinx thing for it. However, it is normally a better idea to
start out with something really simple --
e.g. just modifying the README of your main repo to include your
instructions. In this way, we can iterate on things
faster and scale up to fancier things like Sphinx only when needed. You may
ask me if you are not sure what exactly
should be done.

Thanks!
-Zhen

**Comment by izgzhen** [comment]
@MarkGaox It seems like there is no problem as shown in this issue when I followed your instructions in the resources repo. Does it still exist? How should I reproduce the error?

**Comment by MarkGaox** [comment]
This is because I comment out following lines of code in [Analysis.java](https://github.com/MarkGaox/soot-skeleton/blob/master/src/main/java/SootExample/Analysis.java#L89)

`SootMethod method = testClass.getMethodByName("main");
       System.out.println(method.getModifiers());
       System.out.println(method.retrieveActiveBody());
`

And if you uncomment these three lines, this program is still going to generate the same error. BTW, I think this error is because it couldn't successfully load the target class. So the target SootClass  appears to have no methods in it. Therefore, it throws "main method not found exception" as we discuss above. But I still couldn't find a way to fix this issue. Can you lend me a hand for that?

**Comment by izgzhen** [comment]
@MarkGaox Can you read the diff in my PR carefully and add comments if there is some diff you don't fully understand why?

**Comment by MarkGaox** [comment]
Thank you so much for your help! This issue is solved!
